# Generated by Django 3.2.3 on 2021-05-15 03:34

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ('order',)},
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to='shop/brands/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to='shop/categories/'),
        ),
    ]
