# Generated by Django 3.2.3 on 2021-05-15 03:45

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210515_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to=None),
        ),
    ]
