# Generated by Django 3.2.3 on 2021-05-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sellershop',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=12),
        ),
    ]
