# Generated by Django 3.2.3 on 2021-05-29 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_auto_20210530_0047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellershop',
            old_name='user',
            new_name='seller',
        ),
    ]
